tasks.py

extracted from earlier PR https://github.com/lnbits/lnbits/pull/1369

don't use format string when not needed

---

templates/tpos/tpos.html
views_api.py

Replace getting rates from opennode and use the internal exchange rate tool.

Use internal exchange rate util

---

tasks.py

Check for `tipSplitted` flag on extra
Closes #10

Avoid double tips

---

crud.py
templates/tpos/index.html
templates/tpos/tpos.html
views_api.py

Allow editing an TPos
Adds a button to expand TPOS webpage to fullscreen mode
Closes #4

Allow edits and fullscreen mode

---

__init__.py
config.json

Allow for extensions in a custom path.
__Needs lnbits/lnbits#1940 to be merged and released first !__ 
`min_lnbits_version` in config.json needs to be changed!

external_extension_path

---

views_api.py

fix tpos not working in some cases due to missing lnbits_commit in settings
not sure if the commit version in header is even important - probably not.

FIx TPoS looking for removed lnbits_commit hash

---

migrations.py
models.py
templates/tpos/index.html
templates/tpos/tpos.html
views.py
views_api.py

Closes #18 
Closes #8
Closes #27

Add Items to PoS

---

README.md
templates/tpos/index.html
templates/tpos/tpos.html
views_api.py

Check for wallet key on API endpoint.

check wallet key on endpoint

---

migrations.py
models.py
templates/tpos/index.html
templates/tpos/tpos.html

Add a premium % to ATM exchange rate

add a premium to ATM rate

---

templates/tpos/index.html
templates/tpos/tpos.html

Hotfix for issues 
Fix #44 
Fix #46 
Fix #47 
Fix #49 
Fix #52

Fix issues 0.5.1

---

templates/tpos/tpos.html
views_api.py

This just adds the cart details to the extra (can probably be filtered out on the component to not clutter the UI) so it can be printed!
Another one for 0.5.2

Send details on extra

---

templates/tpos/tpos.html

fixes https://github.com/lnbits/tpos/issues/55
not sure if this is the most elegant or idiomatic code, but it works

fix cart count in collapsed mode

---

templates/tpos/tpos.html

fixes https://github.com/lnbits/tpos/issues/6

add keyboard control

---

templates/tpos/tpos.html

exchange rate premium math was wrong

atm premium fix

---

templates/tpos/tpos.html
views_api.py

Refactor of #23 - 'use LUD-19 withdraw request to top up a wallet (e.g. bolt card)'
Major credits to @gorrdy and @iwarp
Review and further testing is required, by someone with more Boltcard knowledge!

allow withdraw with boltcard

---

templates/tpos/index.html
templates/tpos/tpos.html

I wanted it (#58) so I tried to do it. Some really straighforward changes to quickly accomplish denomination in satoshi.

Satoshi denominated tpos

---

__init__.py
crud.py
lnurl.py
manifest.json
migrations.py
models.py
views_api.py

Sketchy optional toggle to disable the pin for atm mode, secs/mins

Draft: toggle atm

---

models.py

fix create wallet from API

---

config.json
lnurl.py
tasks.py

https://github.com/lnbits/lnbits/pull/2377

chore: rename `websocketUpdater`

---

static/js/tpos.js
templates/tpos/tpos.html

Disable the keypad if there's no exchange rate or the exchange rate is 0

feat: disable keypad if no exchange rate

---

config.json
poetry.lock
views_api.py

fix: use only payment.success property instead of checking status

---

templates/tpos/index.html
templates/tpos/tpos.html

Fix some bugs related to using sats as currency.
Added a loading step until exchange rate is set.
Closes #104
Closes #106
Closes #107

Fix errors 

---

templates/tpos/dialogs.html

fix tip notation

---

static/js/tpos.js
templates/tpos/_cart.html
templates/tpos/_options_fab.html
templates/tpos/dialogs.html

Adds the ability to put carts on hold and restored them!
held carts will be purged after 24 hours
Closes #101

feat: hold carts

---

crud.py
migrations.py
models.py
static/components/receipt.js
static/js/index.js
static/js/tpos.js
templates/tpos/dialogs.html
templates/tpos/index.html
templates/tpos/tpos.html
views.py
views_api.py

Experimental feature for printing receipts on handheld PoS devices.
Closes #133
Closes #20

Add experimental printing feature

---

static/js/tpos.js

Close cart drawer on clear cart
Closes #136

Close cart drawer

---

poetry.lock
pyproject.toml
static/components/receipt.js
static/js/index.js
static/js/tpos.js
templates/tpos/_cart.html
templates/tpos/dialogs.html
templates/tpos/index.html
templates/tpos/tpos.html

Closes #143 
Closes #144
Closes #145
Closes #146
Closes #147
Closes #148

Fix: UI/UX issues on TPOS

---

static/js/tpos.js

Persistent NFC error message
On toast dismiss, restart NFC

Fix NFC error handling

---

pyproject.toml
static/js/tpos.js
templates/tpos/dialogs.html
views_atm.py

Fixed and tested.
Ready for release after merge

Testing and fixing
